openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: localhost:8000
    description: Optional server description, e.g. Main (production) server
paths:
  /patient/all:
    get:
      summary: Returns a list of patients.
      description: Return a Json with a list of patients
      responses:
        '200':    # status code
          description: A JSON array of patients
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: integer
                  data:
                    items:
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        nif:
                          type: string
                        created_at:
                          type: string
                        updated_att:
                          type: string
        '400': # status code
          description: A JSON with status operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: integer
                  data:
                    type: array


  /patient/show/{id}:
    get:
      summary: Endpoint for show a patient
      description: Return a Json with success status when try store a patient and patient data
      responses:
        '200': # status code
          description: A JSON with status operation and data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: integer
                  data:
                    items:
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        nif:
                          type: string
                        created_at:
                          type: string
                        updated_att:
                          type: string
        '400': # status code
          description: A JSON with status operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: integer
                  data:
                    type: array
                    items:





  /patient/store:
    post:
      summary: Endpoint for store a patient
      description: Return a Json with success status when try store a patient
      responses:
        '200': # status code
          description: A JSON array of patients
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /patient/update/{id}:
    post:
      summary: Endpoint for update a patient.
      description: Return a Json with success status when try update a patient
      responses:
        '200': # status code
          description: A JSON with status operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400': # status code
          description: A JSON with status operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string

  /patient/delete/{id}:
    delete:
      summary: Endpoint for delete a patient .
      description: Return a Json with success status when try delete a patient
      responses:
        '200': # status code
          description: A JSON with status operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400': # status code
          description: A JSON with status operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
