openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: localhost:8000
    description: Optional server description, e.g. Main (production) server
paths:
  /diangosis/store:
    get:
      summary: Store a diagnosis
      description: This endpoint store a diagnosis
      responses:
        '200':    # status code
          description: A JSON array of patients
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: integer
        '400':    # status code
          description: The endpoint cant store a diagnosis
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: integer

  /diagnosis/patient/{id}:
    get:
      summary: Returns a list of diagnosis for a patient.
      description: Return a Json with a list of diagnosis of a patient
      responses:
        '200': # status code
          description: A JSON array of patients
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: integer
                  data:
                    items:
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        nif:
                          type: string
                        created_at:
                          type: string
                        updated_att:
                          type: string
